Update debupdate

diff --git a/debupdate b/debupdate
--- a/debupdate
+++ b/debupdate
@@ -1,5 +1,5 @@
 #!/bin/bash
-echo "#v0.48## To use this in cli use"
+echo "#v0.49## To use this in cli use"
 echo "sudo nano /bin/usr/update
 # copy the next 3 lines into it with, and chmod it to 755  
 #!/bin/bash
@@ -53,7 +53,38 @@ sleep 1
 echo ":~${HOST_IP} who -a"
 who -a
 sleep 3
-sudo apt install apt-utils dialog
+
+# Check if apt-utils command is installed
+if ! command -v apt-utils &> /dev/null; then
+  # apt-utils command is not found, install it
+  echo "Installing apt-utils ..."
+  if command -v apt &> /dev/null; then
+    sudo apt update
+    sudo apt install -y apt-utils 
+  elif command -v pacman &> /dev/null; then
+    sudo pacman -Sy apt-utils 
+  else
+    echo "Unable to install apt-utils . Please install it manually."
+ fi
+fi
+echo -e "${GREEN}apt-utils Installed${NC}"
+
+# Check if dialog command is installed
+if ! command -v dialog &> /dev/null; then
+  # bc command is not found, install it
+  echo "Installing dialog..."
+  if command -v apt &> /dev/null; then
+    sudo apt update
+    sudo apt install -y dialog
+  elif command -v pacman &> /dev/null; then
+    sudo pacman -Sy dialog
+  else
+    echo "Unable to install dialog. Please install it manually."
+ fi
+fi
+echo -e "${GREEN}dialog Installed${NC}"
+
+
 # Check if bc command is installed
 if ! command -v bc &> /dev/null; then
   # bc command is not found, install it
@@ -67,7 +98,7 @@ if ! command -v bc &> /dev/null; then
     echo "Unable to install bc. Please install it manually."
  fi
 fi
-echo -e "${GREEN}bc Passed${NC}"
+echo -e "${GREEN}bc Installed${NC}"
 
 # Check if curl command is installed
 if ! command -v curl &> /dev/null; then
@@ -82,7 +113,7 @@ if ! command -v curl &> /dev/null; then
     echo "Unable to install curl. Please install it manually."
  fi
 fi
-echo -e "${GREEN}curl Passed${NC}"
+echo -e "${GREEN}curl Installed${NC}"
 
 # Check if inxi command is installed
 if ! command -v inxi &> /dev/null; then
@@ -97,7 +128,7 @@ if ! command -v inxi &> /dev/null; then
     echo "Unable to install inxi. Please install it manually."
   fi
 fi
-echo -e "${GREEN}inxi Passed${NC}"
+echo -e "${GREEN}inxi Installed${NC}"
 
 # Check if neofetch command is installed
 if ! command -v neofetch &> /dev/null; then
@@ -112,7 +143,7 @@ if ! command -v neofetch &> /dev/null; then
     echo "Unable to install inxi. Please install it manually."
  fi
 fi
-echo -e "${GREEN}neofetch Passed${NC}"
+echo -e "${GREEN}neofetch Installed${NC}"
 
 # Check if speedtest command is installed
 if ! command -v speedtest &> /dev/null; then
@@ -127,7 +158,7 @@ if ! command -v speedtest &> /dev/null; then
     echo "Unable to install speedtest-cli. Please install it manually."
   fi
 fi
-echo -e "${GREEN}speedtest Passed${NC}"
+echo -e "${GREEN}speedtest Installed${NC}"
 
 echo "get-time $USER@$HOSTNAME ($HOST_IP)"
 # Get the current timestamp
