Update rpi-update

diff --git a/rpi-update b/rpi-update
--- a/rpi-update
+++ b/rpi-update
@@ -1,6 +1,6 @@
 #!/bin/bash
 clear
-echo "#c.63###TEST-premerge# To use this in cli use"
+echo "#c.65###TEST-premerge# To use this in cli use"
 echo "sudo nano /bin/usr/update
 # copy the next 3 lines into it with, and chmod it to 755  
 #!/bin/bash
@@ -48,6 +48,21 @@ for ((i=0; i<${#programs[@]}; i++)); do
     fi
     echo -e "${GREEN}$package_name Installed ${MAGENTA}!${NC}"
 done
+
+if ! command -v qemu-guest-agent &> /dev/null; then
+sudo apt install qemu-guest-agent && sudo systemctl enable qemu-guest-agent && sudo systemctl start qemu-guest-agent
+if command -v apt &> /dev/null; then
+            sudo apt update
+            sudo apt install -y qemu-guest-agent
+        elif command -v pacman &> /dev/null; then
+            sudo pacman -Sy qemu-guest-agent
+        else
+            echo "Unable to install, Please install it manually."
+        fi
+    fi
+    echo -e "${GREEN}qemu-guest-agent Installed ${MAGENTA}!${NC}"
+done
+
 
 echo -e "${NC}"
 # Get the uptime of the system
