Update supdate
disabled ssh-copy-key

diff --git a/supdate b/supdate
--- a/supdate
+++ b/supdate
@@ -1,5 +1,5 @@
 #!/bin/bash
-echo "#v.75# To use this in cli use"
+echo "#v.76# To use this in cli use"
 echo "sudo nano /bin/usr/update
 # copy the next 3 lines into it with, and chmod it to 755  
 #!/bin/bash
@@ -9,22 +9,22 @@ echo 'bye'
 echo "#To use run"
 echo "bash update"
 sleep 2
-echo "setting functions"
+#echo "setting functions"
 # Function to check and copy SSH key to a remote host if needed
-function copy_ssh_key() {
-    if [[ ! -f ~/.ssh/id_rsa.pub ]]; then
-        echo "SSH key not found. Generating a new SSH key..."
-        ssh-keygen -t rsa
-    fi
-    # Check if the SSH key is already present on the remote host
-    if ! ssh-add -L | grep -qF "$(cat ~/.ssh/id_rsa.pub)"; then
-        #read -p "Enter the IP address or hostname of the remote host: " ip
-        echo "Current client $ip"
-        ssh-copy-id "$ip"
-    else
-        echo "SSH key is already copied to the remote host. No need to copy again."
-    fi
-}
+#function copy_ssh_key() {
+#    if [[ ! -f ~/.ssh/id_rsa.pub ]]; then
+#        echo "SSH key not found. Generating a new SSH key..."
+#        ssh-keygen -t rsa
+#    fi
+#    # Check if the SSH key is already present on the remote host
+#   if ! ssh-add -L | grep -qF "$(cat ~/.ssh/id_rsa.pub)"; then
+#        #read -p "Enter the IP address or hostname of the remote host: " ip
+#       echo "Current client $ip"
+#        ssh-copy-id "$ip"
+#    else
+#        echo "SSH key is already copied to the remote host. No need to copy again."
+#    fi
+#}
 
 # Function to check if Pi-hole is installed and running on a host
 function check_pihole {
@@ -78,7 +78,7 @@ for ip in $ip_list; do
     # Perform SSH connection to the device
      echo "Connecting to $ip"
      # Call ssh-copy-id function
-    copy_ssh_key
+#off#    copy_ssh_key
     if check_pihole $ip; then
       echo -e "Pi-hole detected on $ip "
       ssh -yt $ip "(curl -s https://git.aevl.net/tek/umupdate/raw/branch/main/rpi-update)|bash"
